CREATE ROLE clicksmile_app WITH LOGIN PASSWORD 'testpassword' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT CONNECT ON DATABASE clicksmile_test TO clicksmile_app;
GRANT USAGE ON SCHEMA public TO clicksmile_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO clicksmile_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO clicksmile_app;
