ALTER TABLE dentista ADD COLUMN bio TEXT;
ALTER TABLE dentista ADD COLUMN clinica VARCHAR(255);
ALTER TABLE dentista ADD COLUMN telefone VARCHAR(50);
ALTER TABLE dentista ADD COLUMN endereco VARCHAR(255);
