ALTER TABLE dentista
DROP COLUMN IF EXISTS endereco;

ALTER TABLE dentista
ADD COLUMN cep VARCHAR(9),
ADD COLUMN logradouro VARCHAR(255),
ADD COLUMN numero VARCHAR(20),
ADD COLUMN complemento VARCHAR(100),
ADD COLUMN bairro VARCHAR(100),
ADD COLUMN cidade VARCHAR(100),
ADD COLUMN estado VARCHAR(2);
