spring.application.name=ClickSmile

# Configurações do MySQL (O Spring fará a conexão usando o mysql-connector-j definido no seu build.gradle)
spring.datasource.url=jdbc:mysql://localhost:3306/click_smile?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Comportamento do Hibernate (Motor do JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect